# Generated by Django 5.2.17 on 2026-08-10 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('visa_class', models.CharField(blank=True, max_length=255)),
                ('id_token', models.TextField(blank=True)),
                ('token_captured_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['applicant_id', 'email'], name='contribute__applica_9e49ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('post_name', models.CharField(blank=True, max_length=255)),
                ('days', models.JSONField(default=list)),
                ('has_error', models.BooleanField(default=False)),
                ('error_string', models.TextField(blank=True)),
                ('times', models.JSONField(default=list)),
                ('raw', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='contribute.applicant')),
            ],
            options={
                'indexes': [models.Index(fields=['applicant', 'created_at'], name='contribute__applica_2ea401_idx'), models.Index(fields=['post_id', 'created_at'], name='contribute__post_id_7b877e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_snapshots', to='contribute.applicant')),
            ],
            options={
                'indexes': [models.Index(fields=['applicant', 'created_at'], name='contribute__applica_5e8b0e_idx')],
            },
        ),
    ]
