# Generated by Django 5.2.17 on 2026-09-10 21:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0006_applicant_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_applicant_id', models.CharField(db_index=True, max_length=64)),
                ('payer_name', models.CharField(blank=True, default='', help_text='Customer / payer name or ID', max_length=128)),
                ('payment_ref', models.CharField(blank=True, db_index=True, default='', help_text='UPI / bank / transaction reference', max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='licensedevice',
            new_name='contribute__install_ed0e9c_idx',
            old_name='contribute__install_8a1b2c_idx',
        ),
        migrations.AddField(
            model_name='paymentclaim',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_claims', to='contribute.applicant'),
        ),
        migrations.AddIndex(
            model_name='paymentclaim',
            index=models.Index(fields=['status', 'created_at'], name='contribute__status_78a8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentclaim',
            index=models.Index(fields=['target_applicant_id', 'status'], name='contribute__target__4f741b_idx'),
        ),
    ]
